{"uuid": "d32095f2-13e2-4fb9-9101-25981779790b", "children": ["89b19f66-81e5-4055-9474-b22d3f9a59cb", "afd81bad-6813-4bc2-873b-b08d3281fe40", "dd6975ac-8465-448d-b17a-f5776f824b63", "246d8e7e-01a8-46b0-a309-4195210b117a", "8d5a2c01-eecb-4881-95ed-1c2473501347", "3ec5b7c5-89ce-4db9-9427-7dd03c81cbf6", "b6b03b74-8dd9-4c80-9468-83a8d48f8c7b"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720266989, "stop": 1657720278206}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720309052, "stop": 1657720309056}], "start": 1657720266989, "stop": 1657720309056}