{"uuid": "acb55daa-4356-40aa-b5af-0cc8824fe096", "children": ["0ba1674e-97a0-4bd4-aaaf-e2dff4ee8f31", "6388e58a-7584-43b1-bdf4-b5f1249eb716", "3d1fe642-61a2-41d4-be7c-1dcc3d2ebf75", "826e7b46-f293-47e1-879f-5ba94af8e8e6", "ddc83513-d183-449c-9f51-85ab527fbffb", "1279bab7-4389-4d9d-81c5-c058fff9c62f", "92285edc-e6ca-4be3-b6b9-3d390d42e050", "36f0c2d1-3e0d-4de2-bf2c-efad6bff71a4", "197bace9-1a23-4e0a-9204-02a90a1935f8", "09783c94-7dac-468a-82cd-bab7347eddf4", "c3a64794-fbc1-4290-9917-ca0c51423678"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720309447, "stop": 1657720314934}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720354573, "stop": 1657720354574}], "start": 1657720309447, "stop": 1657720354574}