{"uuid": "569ee586-c691-46da-8a06-306a230d91f4", "children": ["971dbd31-4594-45a0-b7f5-fa2bd9ea0cda", "f914c88e-23db-4d85-ba2b-56e6a6fa6b91", "d78b9ba9-9dc9-4caa-9d14-cb55f89242ed", "14940128-b095-430d-a5eb-b9148ee6ca17", "7283bc46-0cdf-43da-a031-f3c64a8d779f"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657719633878, "stop": 1657719641842}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 41, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657719658036, "stop": 1657719658038}], "start": 1657719633878, "stop": 1657719658039}