{"uuid": "482e4409-d16e-4957-8d5c-09d9f8bd8200", "children": ["7b6fdcc8-a1fe-4d7b-b481-fd5ee949e21d", "6ca1275c-bd79-42ca-894c-5058b0041728", "39383512-4d9a-4ad8-b72c-a23d842f650b", "6d484cc0-0ac3-4266-a138-43d92696f9be", "c9c346a1-90d4-4ab5-8f25-4c61a7b4e47c", "564439d1-2090-4a5b-b943-24ab1d2c37e0", "324efae6-9633-4c20-a951-9a01bedf08c5"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657719650749, "stop": 1657719659027}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 41, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657719687526, "stop": 1657719687535}], "start": 1657719650749, "stop": 1657719687539}