{"uuid": "3fd8f487-c026-40cf-9366-c0744dfb25d7", "children": ["625e1eea-1f0f-4320-b899-b59688205ff7", "186b35d0-32dc-4a18-9490-75eb095e623a", "a019d732-1bf2-47ca-918c-b328d89a038c", "476576bc-dd89-4f7f-b8dd-72ec29ed4bc8", "a7f25458-2ca2-44c0-971f-a495fef8fcb6"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720689253, "stop": 1657720713526}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720736039, "stop": 1657720736039}], "start": 1657720689253, "stop": 1657720736039}