{"uuid": "40283f84-26a3-43cc-9b9c-67a92e2e6502", "children": ["8d19660b-917c-421f-b329-a081c7b2d284", "2016b924-c34f-4ece-9760-74510d7c143b", "a911dfae-7828-4691-acac-99398fefff35", "f7de1562-df9f-40f4-86c2-ed382b0a3a05", "15046bd4-0cf6-4751-a5b5-1859624eed8b", "97641425-22cc-4e15-a34e-bd674beb1591"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657719652174, "stop": 1657719659918}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 41, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657719680516, "stop": 1657719680524}], "start": 1657719652174, "stop": 1657719680524}