{"uuid": "9cb49aaa-9d9a-4e0d-abb5-04c366d9e5f0", "children": ["a38cf7f4-eef8-4756-8e2c-40b81f4d9775", "38c755fa-7041-4191-bca7-f92d20dafafe", "0cbd4108-4b01-48ca-92c6-8a6748212f4b", "40f7464d-9718-4345-ad5c-a6dd00acad5f", "89cbc070-ca23-46a5-b8f1-699be80a6854", "710ad8df-a188-410f-96bb-17f6a557a2e4", "aa856608-32ee-4a0c-b815-57c0aa1f9534"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720266989, "stop": 1657720284403}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720303642, "stop": 1657720303643}], "start": 1657720266989, "stop": 1657720303643}