{"uuid": "391751f8-b23e-41ab-bb8d-c7bb6b220720", "children": ["c8c4cc64-67e6-451d-96cb-6e3be1f2d1bc", "a305b662-5e12-45c9-9fb5-f66f468480e9", "0206c47b-cbe2-42b4-b37e-498bbf49881c", "bd6de3ea-ccd5-45c9-8146-513c8afe5ad1", "4c20a44a-f669-43e2-91d3-5bf8f5e53ae8", "1887e99a-bd99-40e8-b841-72543ea6685a", "726ef4a8-f098-46cd-9f8a-e2b705c285b5", "4d43e631-f1c0-4f88-aff4-79c11d8b3e0f", "8eff3c8e-789e-4b17-b856-6eb7fe230ea6", "de66a544-e942-452f-ae23-88969091b2f7", "26d8cc50-b952-4664-8cf4-3f0823f8f607", "1de7b475-9f75-4420-bbe7-6cad81b6f5ec"], "befores": [{"name": "init_driver", "status": "passed", "start": 1657720651857, "stop": 1657720659146}], "afters": [{"name": "init_driver::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Class' object has no attribute 'rep_call'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/fixtures.py\", line 899, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/svc/PycharmProjects/SeleniumPythonProject/Framework/tests/conftest.py\", line 45, in init_driver\n    if request.node.rep_call.failed:\n"}, "start": 1657720684769, "stop": 1657720684775}], "start": 1657720651857, "stop": 1657720684775}